dado = (input('Digite algo: '))
print('O tipo primitivo é: ', type(dado))
print('Só tem espaço?: ', dado.isspace())
print('É um número?: ', dado.isnumeric())
print('É alfabetico?: ', dado.isalpha())
print('É alfanúmerico?: ', dado.isalnum())
print('É um dado númerico?: ', dado.isnumeric())
print('Está em maiúscula?: ', dado.isupper())
print('Está em minúsculas?: ', dado.islower())
print('Está capitalizada?: ', dado.istitle())